id: PAD313CC2
initial_creation_type: input
source_metadata:
  title: Candragomin Series
  language: bo
  description: 'Texts by and about the seventh-century Indian master Candragomin (tsandra
    go mi):'
  volume:
    acfbb2c0c3af4fe894a41634420d8ce7:
      title: 'The Fulfilment of All Aspirations: In Praise of Noble Tārā'
      parent: Praise
    cfb78efd954b4eed86a8611719d62079:
      title: 'The Swift Infusion of Blessings: In Praise of the Mahāpaṇḍita Candragomin'
      parent: Praise
created_at: '2022-03-01T02:14:07.728724'
last_modified_at: '2022-03-01T02:14:07.728727'
